spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATABASE_URL_PROD}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 180000
      connection-timeout: 20000
      max-lifetime: 600000
      keepalive-time: 60000

  jpa:
    hibernate:
      ddl-auto: update

server:
  tomcat:
    threads:
      max: 30
      min-spare: 5
    accept-count: 50
    connection-timeout: 20000
