name: CI/CD

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:8-jdk21
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: gradle clean build -x test
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  deploy-production:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PROD }}
        run: railway up --service=${{ secrets.SVC_ID }} --environment=production

  deploy-staging:
    needs: build
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to staging
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_STAGING }}
        run: railway up --service=${{ secrets.SVC_ID }} --environment=staging
